In [4]:
%pip install notebook

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
%pip install -venv pandas jupyter notebook

Using pip 25.0.1 from c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip (python 3.13)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: nv is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).


Jupyter Notebook file created: NumPy_Lab1.ipynb

In [3]:
import numpy as numpyObj

numArr = numpyObj.arange(1, 21, 3)
print("Array:", numArr)


Array: [ 1  4  7 10 13 16 19]


In [6]:
randArr = numpyObj.random.rand(3)
print("Random Numbers bet 0-1:", randArr)


Random Numbers bet 0-1: [0.04261202 0.6996757  0.0758049 ]


In [7]:
A = numpyObj.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# First two rows
print("First two rows:\n", A[:2])

# Last two rows
print("Last two rows:\n", A[1:])


First two rows:
 [[10 20 45]
 [30 12 16]]
Last two rows:
 [[30 12 16]
 [42 17 56]]


In [8]:
a = numpyObj.array([[1, 2], [3, 4]])
b = numpyObj.array([[5, 6], [7, 8]])

# Vertical stack
vertStack = numpyObj.vstack((a, b))
print("Vertical Stack:\n", vertStack)

# Horizontal stack
hstack = numpyObj.hstack((a, b))
print("Horizontal Stack:\n", hstack)

# Split horizontally into 2
horizSplit = numpyObj.hsplit(hstack, 2)
print("Split Arrays:")
for part in horizSplit:
    print(part)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Split Arrays:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [9]:
#6 Matrix multiplication feasibility

X = numpyObj.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = numpyObj.array([[4, 2], [6, 2], [4, 2]])

# Valid multiplication (3x3) x (3x2) → (3x2)
if X.shape[1] == Y.shape[0]:
    result = numpyObj.dot(X, Y)
    print("Matrix Multiplication:\n", result)
else:
    print("Multiplication Not Possible")

# Example of invalid multiplication
Z = numpyObj.array([[1, 2], [3, 4]])  # 2x2
try:
    numpyObj.dot(X, Z)
except ValueError as e:
    print("Invalid multiplication:", e)


Matrix Multiplication:
 [[70 28]
 [70 30]
 [60 26]]
Invalid multiplication: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


In [10]:
#7 Vector x and y operations

x = numpyObj.array([2, -1, -8])
y = numpyObj.array([3, 1, -2])

print("Shape of x:", x.shape)
print("Dimensions of x:", x.ndim)

# Reshape x and y
x_reshaped = x.reshape(3, 1)
y_reshaped = y.reshape(3, 1)

print("x reshaped shape:", x_reshaped.shape)
print("x reshaped ndim:", x_reshaped.ndim)
print("y reshaped ndim:", y_reshaped.ndim)


Shape of x: (3,)
Dimensions of x: 1
x reshaped shape: (3, 1)
x reshaped ndim: 2
y reshaped ndim: 2


In [11]:
#8 Broadcasting with 3*3 matrix

M = numpyObj.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = numpyObj.array([1, 0, 1])

print("Matrix:\n", M)
print("Vector:\n", v)

# Subtraction
print("Broadcast Subtraction:\n", M - v)

# Multiplication
print("Broadcast Multiplication:\n", M * v)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
 [1 0 1]
Broadcast Subtraction:
 [[0 2 2]
 [3 5 5]
 [6 8 8]]
Broadcast Multiplication:
 [[1 0 3]
 [4 0 6]
 [7 0 9]]


#9 NumPy Lab Overview

- **Array Creation:** Demonstrated how to create arrays using arange and random.
- **Indexing/Slicing:** Extracted subsets from 2D arrays.
- **Stacking & Splitting:** Shown both vertical and horizontal operations.
- **Matrix Operations:** Verified multiplication compatibility and handled exceptions.
- **Reshaping:** Vector reshaped and dimensions observed.
- **Broadcasting:** Illustrated subtraction and multiplication over a 3x3 matrix.


#1 Solve using NumPy Linear Algebra
2x1 + 3x2 - 4x3 = 6  
x1 - 4x2 + 0x3 = 8  

In [12]:
from numpy.linalg import solve, matrix_rank

# Add a third equation as 0 = 0 to create 3x3 system
A1 = numpyObj.array([[2, 3, -4],
               [1, -4, 0],
               [0, 0, 0]])  # Added to form square matrix

b1 = numpyObj.array([6, 8, 0])

# Check rank
rankA1 = matrix_rank(A1)
augmentRankA1 = matrix_rank(numpyObj.column_stack((A1, b1)))

print("Rank of A:", rankA1)
print("Rank of [A|b]:", augmentRankA1)

if rankA1 == rankA1 == 3:
    x = solve(A1, b1)
    print("Solution:", x)
elif rankA1 == augmentRankA1:
    print("Infinite solutions.")
else:
    print("No solution.")


Rank of A: 2
Rank of [A|b]: 2
Infinite solutions.


#2 Solve using NumPy Linear Algebra
3y1 - 4y2 + 5y3 = 10  
-y1 + 2y2 - 4y3 = 8  

In [ ]:
A2 = numpyObj.array([[3, -4, 5],
               [-1, 2, -4],
               [0, 0, 0]])

b2 = numpyObj.array([10, 8, 0])

rankA2 = matrix_rank(A2)
augmentRankA2 = matrix_rank(numpyObj.column_stack((A2, b2)))

print("Rank of A2:", rankA2)
print("Rank of [A2|b2]:", augmentRankA2)

if rankA2 == augmentRankA2 and rankA2 == 3:
    y = solve(A2, b2)
    print("Solution:", y)
elif rankA2 == augmentRankA2:
    print("Infinite solutions.")
else:
    print("No solution.")


NameError: name 'np' is not defined