Jupyter Notebook file created: NumPy_Lab1.ipynb

In [1]:
import numpy as np

arr = np.arange(1, 21, 3)
print("Array:", arr)


Array: [ 1  4  7 10 13 16 19]


In [2]:
rand_arr = np.random.rand(3)
print("Random array of shape (3,):", rand_arr)


Random array of shape (3,): [0.31334585 0.96977101 0.25815234]


In [ ]:
A = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# First two rows
print("First two rows:\n", A[:2])

# Last two rows
print("Last two rows:\n", A[1:])


In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stack
vstack = np.vstack((a, b))
print("Vertical Stack:\n", vstack)

# Horizontal stack
hstack = np.hstack((a, b))
print("Horizontal Stack:\n", hstack)

# Split horizontally into 2
hsplit = np.hsplit(hstack, 2)
print("Split Arrays:")
for part in hsplit:
    print(part)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Split Arrays:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [4]:
#6 Matrix multiplication feasibility

X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Valid multiplication (3x3) x (3x2) → (3x2)
if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    print("Matrix Multiplication:\n", result)
else:
    print("Multiplication Not Possible")

# Example of invalid multiplication
Z = np.array([[1, 2], [3, 4]])  # 2x2
try:
    np.dot(X, Z)
except ValueError as e:
    print("Invalid multiplication:", e)


Matrix Multiplication:
 [[70 28]
 [70 30]
 [60 26]]
Invalid multiplication: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


In [5]:
#7 Vector x and y operations

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of x:", x.shape)
print("Dimensions of x:", x.ndim)

# Reshape x and y
x_reshaped = x.reshape(3, 1)
y_reshaped = y.reshape(3, 1)

print("x reshaped shape:", x_reshaped.shape)
print("x reshaped ndim:", x_reshaped.ndim)
print("y reshaped ndim:", y_reshaped.ndim)


Shape of x: (3,)
Dimensions of x: 1
x reshaped shape: (3, 1)
x reshaped ndim: 2
y reshaped ndim: 2


In [6]:
#8 Broadcasting with 3*3 matrix

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([1, 0, 1])

print("Matrix:\n", M)
print("Vector:\n", v)

# Subtraction
print("Broadcast Subtraction:\n", M - v)

# Multiplication
print("Broadcast Multiplication:\n", M * v)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
 [1 0 1]
Broadcast Subtraction:
 [[0 2 2]
 [3 5 5]
 [6 8 8]]
Broadcast Multiplication:
 [[1 0 3]
 [4 0 6]
 [7 0 9]]


#9 NumPy Lab Overview

- **Array Creation:** Demonstrated how to create arrays using arange and random.
- **Indexing/Slicing:** Extracted subsets from 2D arrays.
- **Stacking & Splitting:** Shown both vertical and horizontal operations.
- **Matrix Operations:** Verified multiplication compatibility and handled exceptions.
- **Reshaping:** Vector reshaped and dimensions observed.
- **Broadcasting:** Illustrated subtraction and multiplication over a 3x3 matrix.


#1 Solve using NumPy Linear Algebra
2x1 + 3x2 - 4x3 = 6  
x1 - 4x2 + 0x3 = 8  

In [7]:
from numpy.linalg import solve, matrix_rank

# Add a third equation as 0 = 0 to create 3x3 system
A1 = np.array([[2, 3, -4],
               [1, -4, 0],
               [0, 0, 0]])  # Added to form square matrix

b1 = np.array([6, 8, 0])

# Check rank
rank_A1 = matrix_rank(A1)
aug_rank_A1 = matrix_rank(np.column_stack((A1, b1)))

print("Rank of A:", rank_A1)
print("Rank of [A|b]:", aug_rank_A1)

if rank_A1 == rank_A1 == 3:
    x = solve(A1, b1)
    print("Solution:", x)
elif rank_A1 == aug_rank_A1:
    print("Infinite solutions.")
else:
    print("No solution.")


Rank of A: 2
Rank of [A|b]: 2
Infinite solutions.


#2 Solve using NumPy Linear Algebra
3y1 - 4y2 + 5y3 = 10  
-y1 + 2y2 - 4y3 = 8  

In [ ]:
A2 = np.array([[3, -4, 5],
               [-1, 2, -4],
               [0, 0, 0]])

b2 = np.array([10, 8, 0])

rank_A2 = matrix_rank(A2)
aug_rank_A2 = matrix_rank(np.column_stack((A2, b2)))

print("Rank of A2:", rank_A2)
print("Rank of [A2|b2]:", aug_rank_A2)

if rank_A2 == aug_rank_A2 and rank_A2 == 3:
    y = solve(A2, b2)
    print("Solution:", y)
elif rank_A2 == aug_rank_A2:
    print("Infinite solutions.")
else:
    print("No solution.")
